// viatrumf-scraper-frontend/src/Nettbutikker.tsx
import { useEffect, useState } from "react";
import axios from "axios";
import "./Nettbutikker.css";
import Nettbutikk from "./Nettbutikk.tsx";
import baseurl from "./URL.ts";

function Nettbutikker() {
  const [nettbutikker, setNettbutikker] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [valgtNettbutikk, setValgtNettbutikk] = useState<string | undefined>(
    undefined,
  );

  const sort = (a: string, b: string): number => {
    if (!a) return 1;
    if (!b) return 1;
    return a.toLowerCase().localeCompare(b.toLowerCase());
  };

  useEffect(() => {
    axios
      .get(baseurl + "/nettbutikkar")
      .then((response) => response.data.sort(sort))
      .then((data) => {
        setNettbutikker(data);
        setLoading(false);
      });
  }, []);

  return (
    <div id="app">
      <h1>Historikk for nettbutikkar på Viatrumf</h1>
      <p>
        Usikker på om Viatrumf-bonusen på nettbutikken du vil handle hos har
        gått opp, ned eller er uendra? Sjekk ved å velje butikken i
        nedtrekkslista.
      </p>
      {loading && <h2>Laster...</h2>}
      {!loading && (
        <select
          defaultValue={"Velg"}
          value={valgtNettbutikk}
          onChange={(e) => setValgtNettbutikk(e.target.value)}
        >
          <option value="Velg" disabled>
            Velg nettbutikk
          </option>
          {nettbutikker.map((nettbutikk) => (
            <option value={nettbutikk} key={nettbutikk}>
              {nettbutikk?.replace(/_/g, " ")}
            </option>
          ))}
        </select>
      )}
      {valgtNettbutikk && (
        <button onClick={(_) => setValgtNettbutikk(valgtNettbutikk)}>
          <img id="reloadIcon" src="../public/reload-icon.png" alt="reload" />
        </button>
      )}
      {valgtNettbutikk && <Nettbutikk namn={valgtNettbutikk} />}
    </div>
  );
}
export default Nettbutikker;

// src/components/Nettbutikker.vue
-<template>
  <div>    
    <h1>Historikk for nettbutikkar på Viatrumf</h1>
    <p v-if="!selected">
      Usikker på om Viatrumf-bonusen på nettbutikken du vil handle hos har gått
      opp, ned eller er uendra? Sjekk ved å velje butikken i nedtrekkslista.
    </p>
    <vue-loading v-if="loading" type="spin" color="#d9544e" :size="{ width: '50px', height: '50px' }"></vue-loading>
    <select v-model="selected" v-on:change="selectionChanged">
      <option value="" selected disabled>Velg nettbutikk</option>
      <option
        v-for="nettbutikk in nettbutikker"
        :key="nettbutikk.namn"
        v-bind:value="nettbutikk"
      >
        {{ nettbutikk | removeUnderscore }}
      </option>
    </select>
    <button v-on:click="selectionChanged" class="reload"><img id="reloadIcon" src="@/assets/reload-icon.png" alt="reload" /></button>
   
    <Nettbutikk :namn="selected" :innslag="selectedNettbutikk" />
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import axios from 'axios'
import Nettbutikk from '@/components/Nettbutikk.vue'
import { VueLoading } from 'vue-loading-template'

@Component({
  components: {
    Nettbutikk,
    VueLoading
  }
})
export default class Nettbutikker extends Vue {
  private baseurl = 'https://viatrumf-scraper-bff-xgjgr2ubbq-ew.a.run.app'
  private nettbutikker = []
  private selected = ''
  private selectedNettbutikk = []
  private loading = true

  selectionChanged(): void {
    axios
      .get(this.baseurl + '/nettbutikkar/' + this.selected)
      .then(response => (this.selectedNettbutikk = response.data))
  }

  sort(a: string, b: string): number {
    if (!a) return 1
    if (!b) return 1
    return a.toLowerCase().localeCompare(b.toLowerCase())
  }

  mounted() {
    axios
      .get(this.baseurl + '/nettbutikkar')
      .then(response => response.data.sort(this.sort))
      .then(data => {
        this.nettbutikker = data
        this.loading = false
      });
  }
}
</script>

<style scoped>

button.reload {
  border: none;
  background-color: inherit;
  padding: 1px;
  margin: 0 4px 4px 4px;
  font-size: 0.7em;
  cursor: pointer;
}

select {
  background-color: inherit;
}

img#reloadIcon {
  width: 1em;
  height: 1em
}

</style>
