// src/Nettbutikker.tsx
import { useEffect, useState } from "react";
import axios from "axios";
import "./Nettbutikker.css";
import Nettbutikk from "./Nettbutikk.tsx";
import { backend } from "./URL.ts";
import { trim } from "./Trim.ts";

function Nettbutikker() {
  const [nettbutikker, setNettbutikker] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [valgtNettbutikk, setValgtNettbutikk] = useState<string | undefined>(
    undefined,
  );

  const sort = (a: string, b: string): number => {
    if (!a) return 1;
    if (!b) return 1;
    return a.toLowerCase().localeCompare(b.toLowerCase());
  };

  useEffect(() => {
    axios
      .get(backend + "/nettbutikkar")
      .then((response) => response.data.sort(sort))
      .then((data) => {
        setNettbutikker(data);
        setLoading(false);
      });
  }, []);

  return (
    <>
      <h1>Historikk for nettbutikkar på Viatrumf</h1>
      {!valgtNettbutikk && (
        <p>
          Usikker på om Viatrumf-bonusen på nettbutikken du vil handle hos har
          gått opp, ned eller er uendra? Sjekk ved å velje butikken i
          nedtrekkslista.
        </p>
      )}
      {loading && <h2>Laster...</h2>}
      {!loading && (
        <select
          defaultValue={"Velg"}
          value={valgtNettbutikk}
          onChange={(e) => setValgtNettbutikk(e.target.value)}
        >
          <option value="Velg" disabled>
            Velg nettbutikk
          </option>
          {nettbutikker.map((nettbutikk) => (
            <option value={nettbutikk} key={nettbutikk}>
              {trim(nettbutikk)}
            </option>
          ))}
        </select>
      )}
      {valgtNettbutikk && <Nettbutikk namn={valgtNettbutikk} />}
    </>
  );
}
export default Nettbutikker;

// src/components/Nettbutikker.vue
-<template>
  <div>
    <loading :active.sync="isLoading" />
    <h1>Historikk for nettbutikkar på Viatrumf</h1>
    <p>
      Usikker på om Viatrumf-bonusen på nettbutikken du vil handle hos har gått
      opp, ned eller er uendra? Sjekk ved å velje butikken i nedtrekkslista.
    </p>
    <select v-model="selected" v-on:change="selectionChanged">
      <option value="" selected disabled>Velg nettbutikk</option>
      <option
        v-for="nettbutikk in nettbutikker"
        :key="nettbutikk.namn"
        v-bind:value="nettbutikk"
      >
        {{ nettbutikk | removeUnderscore }}
      </option>
    </select>
    <Nettbutikk :namn="selected" :innslag="selectedNettbutikk" />
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import axios from 'axios'
import Nettbutikk from '@/components/Nettbutikk.vue'

import Loading from 'vue-loading-overlay'
import 'vue-loading-overlay/dist/vue-loading.css'

@Component({
  components: {
    Nettbutikk,
    Loading
  }
})
export default class Nettbutikker extends Vue {
  private baseurl = 'https://viatrumf-scraper-bff-xgjgr2ubbq-ew.a.run.app'
  private nettbutikker = []
  private selected = ''
  private selectedNettbutikk = []
  private isLoading = true

  selectionChanged(): void {
    axios
      .get(this.baseurl + '/nettbutikkar/' + this.selected)
      .then(response => (this.selectedNettbutikk = response.data))
  }

  sort(a: string, b: string): number {
    if (!a) return 1
    if (!b) return 1
    return a.toLowerCase().localeCompare(b.toLowerCase())
  }

  mounted() {
    axios
      .get(this.baseurl + '/nettbutikkar')
      .then(response => response.data.sort(this.sort))
      .then(data => {
        this.nettbutikker = data
        this.isLoading = false
      });
  }
}
</script>
